import { CrudAPI, iCrud } from '../crud'

import { InnowayApiService } from '../../innoway-api.service'

export interface iBillActivity extends iCrud {
    action?: "BILL_SENT_SUCCESSFULLY" | "BILL_MODIFIED_AT_SENT_SUCCESSFULLY" | "BILL_CANCELLED_AT_SENT_SUCCESSFULLY" | "BILL_DISTRIBUTED" | "BILL_WAITING_FOR_CONFIRMATION" | "BILL_MODIFIED_AT_WAITING_FOR_CONFIRMATION" | "BILL_CANCELLED_AT_WAITING_FOR_CONFIRMATION" | "BILL_CONFIRMED" | "BILL_MODIFIED_AT_BILL_CONFIRMED" | "BILL_CANCELLED_AT_BILL_CONFIRMED" | "BILL_PICKING_UP" | "BILL_MODIFIED_AT_PICKING_UP" | "BILL_CANCELLED_AT_PICKING_UP" | "BILL_RECEIVED" | "BILL_MODIFIED_AT_RECEIVED" | "BILL_CANCELLED_AT_RECEIVED" | "BILL_PROCESSING" | "BILL_MODIFIED_AT_PROCESSING" | "BILL_CANCELLED_AT_PROCESSING" | "BILL_PREPARED" | "BILL_MODIFIED_AT_PREPARED" | "BILL_CANCELLED_AT_PREPARED" | "BILL_SENT_SHIPPER" | "BILL_MODIFIED_AT_SENT_SHIPPER" | "BILL_CANCELLED_AT_SENT_SHIPPER" | "BILL_DELIVERING" | "BILL_MODIFIED_AT_DELIVERING" | "BILL_CANCELLED_AT_DELIVERING" | "BILL_PAID" | "BILL_MODIFIED_AT_PAID" | "BILL_COLLECTED_MONEY" | "BILL_MODIFIED_AT_COLLECTED_MONEY",
    brand_id?: string,
    bill_id?: string,
    employee_id?: string,
    note?: string,
}

export class BillActivity extends CrudAPI<iBillActivity> {
    constructor(
        public api: InnowayApiService
    ) {
        super(api, 'bill_activity')
    }
}

export const ActivityEnum = {
    BILL_SENT_SUCCESSFULLY: 'BILL_SENT_SUCCESSFULLY',
    BILL_DISTRIBUTED: 'BILL_DISTRIBUTED',

    BILL_WAITING_FOR_CONFIRMATION: 'BILL_WAITING_FOR_CONFIRMATION',
    BILL_MODIFIED_AT_WAITING_FOR_CONFIRMATION: 'BILL_MODIFIED_AT_WAITING_FOR_CONFIRMATION',
    BILL_CANCELLED_AT_WAITING_FOR_CONFIRMATION: 'BILL_CANCELLED_AT_WAITING_FOR_CONFIRMATION',

    BILL_CONFIRMED: 'BILL_CONFIRMED',
    BILL_MODIFIED_AT_BILL_CONFIRMED: 'BILL_MODIFIED_AT_BILL_CONFIRMED',
    BILL_CANCELLED_AT_BILL_CONFIRMED: 'BILL_CANCELLED_AT_BILL_CONFIRMED',

    BILL_PICKING_UP: 'BILL_PICKING_UP',
    BILL_MODIFIED_AT_PICKING_UP: 'BILL_MODIFIED_AT_PICKING_UP',
    BILL_CANCELLED_AT_PICKING_UP: 'BILL_CANCELLED_AT_PICKING_UP',

    BILL_RECEIVED: 'BILL_RECEIVED',
    BILL_MODIFIED_AT_RECEIVED: 'BILL_MODIFIED_AT_RECEIVED',
    BILL_CANCELLED_AT_RECEIVED: 'BILL_CANCELLED_AT_RECEIVED',

    BILL_PROCESSING: 'BILL_PROCESSING',
    BILL_MODIFIED_AT_PROCESSING: 'BILL_MODIFIED_AT_PROCESSING',
    BILL_CANCELLED_AT_PROCESSING: 'BILL_CANCELLED_AT_PROCESSING',

    BILL_PREPARED: 'BILL_PREPARED',
    BILL_MODIFIED_AT_PREPARED: 'BILL_MODIFIED_AT_PREPARED',
    BILL_CANCELLED_AT_PREPARED: 'BILL_CANCELLED_AT_PREPARED',

    BILL_SENT_SHIPPER: 'BILL_SENT_SHIPPER',
    BILL_MODIFIED_AT_SENT_SHIPPER: 'BILL_MODIFIED_AT_SENT_SHIPPER',
    BILL_CANCELLED_AT_SENT_SHIPPER: 'BILL_CANCELLED_AT_SENT_SHIPPER',

    BILL_DELIVERING: 'BILL_DELIVERING',
    BILL_MODIFIED_AT_DELIVERING: 'BILL_MODIFIED_AT_DELIVERING',
    BILL_CANCELLED_AT_DELIVERING: 'BILL_CANCELLED_AT_DELIVERING',

    BILL_PAID: 'BILL_PAID',
    BILL_MODIFIED_AT_PAID: 'BILL_MODIFIED_AT_PAID',

    BILL_COLLECTED_MONEY: 'BILL_COLLECTED_MONEY',
    BILL_MODIFIED_AT_COLLECTED_MONEY: 'BILL_MODIFIED_AT_COLLECTED_MONEY'
}